<?php
/**
 * Copyright © Craven Dunnill. All rights reserved.
 */
?>
<!-- ko component: { name: 'subtotal.totals', params: { $parent: $data, $root: $root }} --><!-- /ko -->

<template id="subtotal.totals">
	<div class="amount price-container">
		<!-- ko if: displaySubtotal() -->
			<!-- ko if: display_cart_subtotal_excl_tax -->
				<span class="price-wrapper" data-bind="html: cart().subtotal_excl_tax"></span>
			<!-- /ko -->

			<!-- ko if: !display_cart_subtotal_excl_tax && display_cart_subtotal_incl_tax -->
				<span class="price-wrapper" data-bind="html: cart().subtotal_incl_tax"></span>
			<!-- /ko -->

			<!-- ko if: !display_cart_subtotal_excl_tax && !display_cart_subtotal_incl_tax -->
				<span class="price-wrapper price-including-tax"
					  data-bind="attr: { 'data-label': $t('Incl. Tax') }, html: cart().subtotal_incl_tax">
				</span>

				<span class="price-wrapper price-excluding-tax"
					  data-bind="attr: { 'data-label': $t('Excl. Tax') }, html: cart().subtotal_excl_tax">
				</span>
			<!-- /ko -->
		<!-- /ko -->
		<!-- ko ifnot: displaySubtotal() -->
			<span class="mark msrp" data-bind="text: $t('Order total will be displayed before you submit the order')"></span>
		<!-- /ko -->
	</div>
</template>