<?php
/**
 * Copyright © Craven Dunnill. All rights reserved.
 */
?>
<div class="cd-product-item">
	<div class="cd-product-image">
		<!-- ko if: product_has_url -->
		<a data-bind="attr: {href: product_url, title: product_name}" tabindex="-1" class="product-item-photo">
			<!-- ko template: {name: 'Magento_Catalog/product/image_with_borders', data: $parent.getItemProductImageData(item) } --><!-- /ko -->
		</a>
		<!-- /ko -->
		<!-- ko ifnot: product_has_url -->
		<span class="product-item-photo" data-bind="attr: {'title': product_name}">
			<!-- ko template: {name: 'Magento_Catalog/product/image_with_borders', data: $parent.getItemProductImageData(item) } --><!-- /ko -->
		</span>
		<!-- /ko -->
	</div>

	<div class="cd-product-details">
		<div class="cd-product-name">
			<!-- ko if: product_has_url -->
			<a data-bind="attr: {href: product_url}, html: product_name"></a>
			<!-- /ko -->
			<!-- ko ifnot: product_has_url -->
			<span data-bind="html: product_name"></span>
			<!-- /ko -->
		</div>

		<!-- ko if: options.length -->
		<div class="product options" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
			<span data-role="title" class="toggle"><!-- ko text: $t('See Details') --><!-- /ko --></span>

			<div data-role="content" class="content">
				<strong class="subtitle"><!-- ko text: $t('Options Details') --><!-- /ko --></strong>
				<dl class="product options list">
					<!-- ko foreach: { data: options, as: 'option' } -->
					<dt class="label"><!-- ko text: option.label --><!-- /ko --></dt>
					<dd class="values">
						<!-- ko if: Array.isArray(option.value) -->
						<span data-bind="html: option.value.join('<br>')"></span>
						<!-- /ko -->
						<!-- ko if: (!Array.isArray(option.value) && ['file', 'html'].includes(option.option_type)) -->
						<span data-bind="html: option.value"></span>
						<!-- /ko -->
						<!-- ko if: (!Array.isArray(option.value) && !['file', 'html'].includes(option.option_type)) -->
						<span data-bind="text: option.value"></span>
						<!-- /ko -->
					</dd>
					<!-- /ko -->
				</dl>
			</div>
		</div>
		<!-- /ko -->

		<div class="cd-product-price">
			<!-- ko if: canApplyMsrp -->
			<div class="details-map">
				<span class="label" data-bind="text: $t('Price')"></span>
				<span class="value" data-bind="text: $t('See price before order confirmation.')"></span>
			</div>
			<!-- /ko -->
			<!-- ko ifnot: canApplyMsrp -->
			<div class="price-container">
				<span class="price-wrapper" data-bind="html: product_price"></span>
			</div>
			<!-- /ko -->
		</div>

		<div class="cd-product-qty">
			<!-- ko text: 'Qty: ' + qty --><!-- /ko -->
		</div>

		<div class="product actions">
			<!-- ko if: is_visible_in_site_visibility -->
			<div class="primary">
				<a data-bind="attr: {href: configure_url, title: $t('Edit item')}" class="action edit">
					<span data-bind="text: $t('Edit')"></span>
				</a>
			</div>
			<!-- /ko -->
			<div class="secondary">
				<a href="#" data-bind="attr: {'data-cart-item': item_id, title: $t('Remove item')}"
				   class="action delete">
					<span data-bind="text: $t('Remove')"></span>
				</a>
			</div>
		</div>
	</div>
</div>
<!-- ko if: $data.message -->
<div class="message notice">
	<div data-bind="text: $data.message"></div>
</div>
<!-- /ko -->